// Command spec prints the OpenAPI 3.1 document to stdout. The committed
// apps/api/openapi/openapi.yaml is generated by `pnpm gen`; CI fails on
// drift, so the spec can never lag the code.
package main

import (
	"fmt"
	"os"

	"github.com/gofiber/fiber/v3"

	"github.com/kungal/kungal-link-shortener/apps/api/internal/httpapi"
)

func main() {
	app := fiber.New()
	// Nil deps: handlers never run during spec export.
	api := httpapi.NewAPI(app, httpapi.Deps{})
	yaml, err := api.OpenAPI().YAML()
	if err != nil {
		fmt.Fprintln(os.Stderr, "openapi yaml:", err)
		os.Exit(1)
	}
	os.Stdout.Write(yaml)
}
