/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin OIDC login
         * @description Returns the discovered authorization endpoint and public client parameters the browser needs to start the PKCE authorization-code flow. Contains no secrets.
         */
        get: operations["auth-login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current identity
         * @description Returns the authenticated identity resolved from the session cookie, or 401 when anonymous.
         */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an authorization code for a session
         * @description Exchanges {code, code_verifier} at the OP token endpoint, verifies the access token, stores the tokens in a server-side session, and sets the httpOnly session cookie. The browser never receives tokens.
         */
        post: operations["create-session"];
        /**
         * Log out
         * @description Deletes the server-side session and clears the session cookie. Idempotent.
         */
        delete: operations["delete-session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports that the process is up. Does not touch the database.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List S2S API keys */
        get: operations["list-keys"];
        put?: never;
        /** Mint an S2S API key (plaintext shown exactly once) */
        post: operations["create-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an S2S API key permanently */
        delete: operations["delete-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Disable or re-enable an S2S API key */
        put: operations["set-key-disabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List short links (one page, filtered and sorted server-side)
         * @description Returns one page of the link inventory, each row carrying its visit aggregates for the requested window, plus the total the filters match. Search, status and sort all resolve in the database: the inventory grows without bound, so a client that filtered its own page would only ever search the rows it happened to be holding.
         */
        get: operations["list-links"];
        put?: never;
        /** Create a short link */
        post: operations["create-link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{alias}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visit stats for one link (hourly buckets + recent visits) */
        get: operations["link-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a short link (full editable field set) */
        put: operations["update-link"];
        post?: never;
        /** Delete a short link (visits and buckets cascade) */
        delete: operations["delete-link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s2s/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create (or reuse) a short link
         * @description Authenticated by a Bearer API key minted in the dashboard. When alias is empty and reuse is not disabled, an existing active plain link for the same destination is returned instead of minting a duplicate.
         */
        post: operations["s2s-create-link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s2s/links/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a short link by alias */
        get: operations["s2s-get-link"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s2s/stats/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch daily visit stats for a set of aliases
         * @description Per-alias daily totals, deduplicated human visitor counts and declared-bot hits over an inclusive JST date range (at most 92 days, at most 500 aliases). Days without traffic are omitted; an alias that does not exist yields an empty array rather than failing the batch.
         */
        post: operations["s2s-daily-stats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard aggregates (totals, traffic series, source and referrer breakdowns) */
        get: operations["stats-overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthLoginOutputBody.json
             */
            readonly $schema?: string;
            /** @description OP authorization endpoint (from discovery) */
            authorization_endpoint: string;
            client_id: string;
            redirect_uri: string;
            /** @description space-delimited scopes to request */
            scope: string;
        };
        BucketDTO: {
            /** Format: date-time */
            bucket_start: string;
            /** Format: int64 */
            unique_ips: number;
            /** Format: int64 */
            visits: number;
        };
        CreateKeyInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateKeyInputBody.json
             */
            readonly $schema?: string;
            /** @description Which product this key belongs to, e.g. "kungal" */
            name: string;
        };
        CreateKeyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateKeyOutputBody.json
             */
            readonly $schema?: string;
            key: components["schemas"]["KeyDTO"];
            /** @description The full API key. Shown exactly once — store it now. */
            plaintext: string;
        };
        CreateLinkBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateLinkBody.json
             */
            readonly $schema?: string;
            /** @description Custom alias (4-32 chars of [A-Za-z0-9_-]); empty = random */
            alias?: string;
            description?: string;
            /** @description Absolute http(s) URL to redirect to */
            destination_url: string;
            /**
             * Format: date-time
             * @description RFC3339; null/absent = never expires
             */
            expires_at?: string;
            /** @description Append the incoming query string to the destination */
            forward_params?: boolean;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_visits?: number;
        };
        CreateSessionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateSessionInputBody.json
             */
            readonly $schema?: string;
            /** @description authorization code from the OP redirect */
            code: string;
            /** @description PKCE verifier matching the sent challenge */
            code_verifier: string;
        };
        CreateSessionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateSessionOutputBody.json
             */
            readonly $schema?: string;
            is_admin: boolean;
            name: string;
            roles: string[] | null;
            /** Format: int64 */
            user_id: number;
        };
        DailyStatDTO: {
            /**
             * Format: int64
             * @description Hits that day from user agents announcing an automated client (crawlers, link previews, HTTP libraries); counted in total, never in uniques
             */
            bots: number;
            /** @description JST calendar day (YYYY-MM-DD) */
            date: string;
            /**
             * Format: int64
             * @description All hits recorded that day, bots included
             */
            total: number;
            /**
             * Format: int64
             * @description Distinct visitor fingerprints that day, declared bots excluded
             */
            uniques: number;
        };
        DailyStatsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DailyStatsBody.json
             */
            readonly $schema?: string;
            /** @description Short link aliases to report on */
            aliases: string[] | null;
            /**
             * Format: date
             * @description First JST day, inclusive (YYYY-MM-DD)
             */
            from: string;
            /**
             * Format: date
             * @description Last JST day, inclusive (YYYY-MM-DD)
             */
            to: string;
        };
        DailyStatsResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DailyStatsResult.json
             */
            readonly $schema?: string;
            /** @description Alias to its days with traffic, ascending; unknown aliases map to an empty array */
            stats: {
                [key: string]: components["schemas"]["DailyStatDTO"][] | null;
            };
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Liveness status
             * @example ok
             */
            status: string;
            /**
             * @description Build version
             * @example dev
             */
            version: string;
        };
        KeyDTO: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            created_by: number;
            disabled: boolean;
            /** Format: int64 */
            id: number;
            /** @description First characters of the plaintext, for display */
            key_prefix: string;
            /** Format: date-time */
            last_used_at: string | null;
            name: string;
        };
        KeyListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/KeyListOutputBody.json
             */
            readonly $schema?: string;
            keys: components["schemas"]["KeyDTO"][] | null;
        };
        LinkDTO: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LinkDTO.json
             */
            readonly $schema?: string;
            alias: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: int64
             * @description IdP user id; 0 for S2S-created links
             */
            created_by: number;
            /** @description "dashboard" or the S2S API key name */
            created_via: string;
            description: string;
            destination_url: string;
            /** Format: date-time */
            expires_at: string | null;
            forward_params: boolean;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            last_visited_at: string | null;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_visits: number;
            /** @description Advertised short URL (public base + /s/alias) */
            short_url: string;
            /**
             * Format: int32
             * @description 0=active 1=disabled 2=archived
             */
            status: number;
            /** Format: int64 */
            visit_count: number;
        };
        LinkListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LinkListOutputBody.json
             */
            readonly $schema?: string;
            links: components["schemas"]["LinkRowDTO"][] | null;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            range_days: number;
            /**
             * Format: int64
             * @description rows matching the filters, across every page
             */
            total: number;
            /**
             * Format: int64
             * @description at least 1, so an empty inventory still reads as page 1 of 1
             */
            total_pages: number;
        };
        LinkRowDTO: {
            link: components["schemas"]["LinkDTO"];
            /** Format: int64 */
            range_unique: number;
            /** Format: int64 */
            range_visits: number;
        };
        LinkStatsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LinkStatsOutputBody.json
             */
            readonly $schema?: string;
            buckets: components["schemas"]["BucketDTO"][] | null;
            link: components["schemas"]["LinkDTO"];
            /** Format: int64 */
            range_days: number;
            /** Format: int64 */
            range_unique: number;
            /** Format: int64 */
            range_visits: number;
            recent: components["schemas"]["VisitDTO"][] | null;
            referrers: components["schemas"]["ReferrerDTO"][] | null;
            /**
             * Format: int64
             * @description all-time distinct IPs
             */
            unique_visitors: number;
        };
        MeOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MeOutputBody.json
             */
            readonly $schema?: string;
            is_admin: boolean;
            name: string;
            roles: string[] | null;
            /** Format: int64 */
            user_id: number;
        };
        OkOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OkOutputBody.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        OverviewOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverviewOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            range_days: number;
            /** Format: date-time */
            range_start: string;
            referrers: components["schemas"]["ReferrerDTO"][] | null;
            /** @description hourly buckets summed across links; sparse (empty hours are omitted) */
            series: components["schemas"]["BucketDTO"][] | null;
            sources: components["schemas"]["OverviewSourceDTO"][] | null;
            totals: components["schemas"]["OverviewTotalsDTO"];
        };
        OverviewSourceDTO: {
            created_via: string;
            /** Format: int64 */
            links: number;
            /** Format: int64 */
            range_visits: number;
        };
        OverviewTotalsDTO: {
            /** Format: int64 */
            active_keys: number;
            /** Format: int64 */
            active_links: number;
            /** Format: int64 */
            all_time_visits: number;
            /** Format: int64 */
            archived_links: number;
            /** Format: int64 */
            disabled_links: number;
            /** Format: int64 */
            keys: number;
            /** Format: int64 */
            links: number;
            /**
             * Format: int64
             * @description unique IPs in the preceding window of equal length
             */
            prev_unique: number;
            /**
             * Format: int64
             * @description visits in the preceding window of equal length
             */
            prev_visits: number;
            /** Format: int64 */
            range_unique: number;
            /** Format: int64 */
            range_visits: number;
        };
        ReferrerDTO: {
            /** @description referrer host, "" for direct traffic */
            host: string;
            /** Format: int64 */
            visits: number;
        };
        S2sCreateLinkInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/S2sCreateLinkInputBody.json
             */
            readonly $schema?: string;
            /** @description Custom alias (4-32 chars of [A-Za-z0-9_-]); empty = random */
            alias?: string;
            description?: string;
            /** @description Absolute http(s) URL to redirect to */
            destination_url: string;
            /**
             * Format: date-time
             * @description RFC3339; null/absent = never expires
             */
            expires_at?: string;
            /** @description Append the incoming query string to the destination */
            forward_params?: boolean;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_visits?: number;
            /** @description Default true. False forces a new link even when an equivalent exists. */
            reuse?: boolean;
        };
        S2sLinkOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/S2sLinkOutputBody.json
             */
            readonly $schema?: string;
            alias: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: int64
             * @description IdP user id; 0 for S2S-created links
             */
            created_by: number;
            /** @description "dashboard" or the S2S API key name */
            created_via: string;
            description: string;
            destination_url: string;
            /** Format: date-time */
            expires_at: string | null;
            forward_params: boolean;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            last_visited_at: string | null;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_visits: number;
            /** @description True when an existing equivalent link was returned instead of a new one */
            reused: boolean;
            /** @description Advertised short URL (public base + /s/alias) */
            short_url: string;
            /**
             * Format: int32
             * @description 0=active 1=disabled 2=archived
             */
            status: number;
            /** Format: int64 */
            visit_count: number;
        };
        SetKeyDisabledInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetKeyDisabledInputBody.json
             */
            readonly $schema?: string;
            disabled: boolean;
        };
        UpdateLinkInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateLinkInputBody.json
             */
            readonly $schema?: string;
            description: string;
            destination_url: string;
            /**
             * Format: date-time
             * @description null clears the expiry
             */
            expires_at: string | null;
            forward_params: boolean;
            /** Format: int64 */
            max_visits: number;
            /**
             * Format: int32
             * @description 0=active 1=disabled 2=archived
             */
            status: number;
        };
        VisitDTO: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            ip: string;
            is_unique: boolean;
            referer: string;
            user_agent: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                shortlink_session?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-key-disabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetKeyDisabledInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-links": {
        parameters: {
            query?: {
                page?: number;
                /** @description rows per page (1-100) */
                per_page?: number;
                /** @description case-insensitive substring of the alias, destination or description */
                q?: string;
                /** @description 0=active 1=disabled 2=archived, -1=any */
                status?: number;
                /** @description range=in-window visits, total=all-time visits, created=newest first, alias=A-Z */
                sort?: "range" | "total" | "created" | "alias";
                /** @description days the per-row visit aggregates cover */
                range?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLinkBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "link-stats": {
        parameters: {
            query?: {
                /** @description days of buckets to return (1-30, default 7) */
                range?: number;
            };
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkStatsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLinkInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "s2s-create-link": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer slk_... */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["S2sCreateLinkInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["S2sLinkOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "s2s-get-link": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer slk_... */
                Authorization?: string;
            };
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkDTO"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "s2s-daily-stats": {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer slk_... */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyStatsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStatsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stats-overview": {
        parameters: {
            query?: {
                /** @description days covered by the window (1-30, default 7) */
                range?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
